export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGEDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL'